import { DevrelItem } from "@/types/devrel";

// Sizes generated by scripts/thumbs.mjs; keep in sync.
const THUMB_WIDTHS = [480, 960] as const;

export function thumbSrc(item: DevrelItem, width: (typeof THUMB_WIDTHS)[number] = 960) {
  return `/devrel/${item.thumbnail.replace(/\.[^.]+$/, "")}-${width}.webp`;
}

export function thumbSrcSet(item: DevrelItem) {
  return THUMB_WIDTHS.map((w) => `${thumbSrc(item, w)} ${w}w`).join(", ");
}
